{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# definição das cadeiras que o aluno pode se matricular a partir do histórico\n",
    "def prox_cadeiras(historico, sem_prerequisito):\n",
    "    #seleciona na coluna de prerequisitos as cadeiras que já foram pagas\n",
    "    possibilidades = prerequisitos.loc[prerequisitos['codigo_prerequisito'].isin(historico)]\n",
    "    possibilidades = possibilidades[['codigo_disciplina']]\n",
    "    for cadeira in possibilidades.codigo_disciplina:\n",
    "        if not cadeira_paga(cadeira,historico):\n",
    "            prerequisitos_cadeira = prerequisitos.loc[prerequisitos['codigo_disciplina'] == cadeira]\n",
    "\n",
    "            pre=prerequisitos_cadeira['codigo_prerequisito'].isin(historico)\n",
    "            prerequisitos_pagos = True\n",
    "            for  c in pre:\n",
    "                if c == False:\n",
    "                    prerequisitos_pagos = False\n",
    "                    break\n",
    "            if prerequisitos_pagos:\n",
    "                sem_prerequisito.append(cadeira)\n",
    "    return sem_prerequisito\n",
    "\n",
    "# definição das cadeiras que o aluno pode se matricular a partir do histórico\n",
    "def prox_cadeiras_nome(historico, proximas_cadeiras, prerrequisitos):\n",
    "    #seleciona na coluna de prerequisitos as cadeiras que já foram pagas\n",
    "    possibilidades = prerrequisitos.loc[prerrequisitos[prerrequisitos.columns[1]].isin(historico.index)]\n",
    "    possibilidades = possibilidades[[possibilidades.columns[0]]]\n",
    "    for cadeira in list(possibilidades[possibilidades.columns[0]]):\n",
    "        if not cadeira_paga(cadeira,historico.index):\n",
    "            prerrequisitos_cadeira = prerrequisitos.loc[prerrequisitos[prerrequisitos.columns[0]] == cadeira]\n",
    "            pre=prerrequisitos_cadeira[prerrequisitos_cadeira.columns[1]].isin(historico.index)\n",
    "            \n",
    "            prerrequisitos_pagos = True\n",
    "            for c in pre:\n",
    "                if c == False:\n",
    "                    prerrequisitos_pagos = False\n",
    "                    break\n",
    "            if prerrequisitos_pagos and cadeira not in proximas_cadeiras:\n",
    "                proximas_cadeiras.append(cadeira)\n",
    "    return proximas_cadeiras\n",
    "\n",
    "# retorna quais cadeiras o aluno já foi aprovado\n",
    "def cadeira_paga(cadeira, historico):\n",
    "    cadeira_isin_historico = False\n",
    "    for cadeira_paga in historico:\n",
    "        if cadeira_paga == cadeira:\n",
    "            cadeira_isin_historico = True\n",
    "            break\n",
    "    return cadeira_isin_historico\n",
    "\n",
    "# retorna o código de uma cadeira a partir do seu nome\n",
    "def nomeCadeira_para_cod(conj_cadeiras, cod_nome_df):\n",
    "    cod_conj_cadeiras = []\n",
    "    for cadeira in conj_cadeiras:\n",
    "        aux = cod_nome_df.loc[cod_nome_df['Nome_Disciplina'] == cadeira]\n",
    "        aux = aux[['Cod_Disciplina']]\n",
    "        if not aux.empty:\n",
    "            cod_conj_cadeiras.append(aux.iloc[0]['Cod_Disciplina'])\n",
    "    return cod_conj_cadeiras\n",
    "\n",
    "# retorna o nome de uma cadeira a partir do seu código\n",
    "def cod_para_nomeCadeira(conj_cadeiras, cod_nome_df):\n",
    "    cod_conj_cadeiras = []\n",
    "    for cadeira in conj_cadeiras:\n",
    "        aux = cod_nome_df.loc[cod_nome_df['Cod_Disciplina'] == cadeira]\n",
    "        aux = aux[['Nome_Disciplina']]\n",
    "    \n",
    "        if not aux.empty:\n",
    "            cod_conj_cadeiras.append(aux.iloc[0]['Nome_Disciplina'])\n",
    "    return cod_conj_cadeiras"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
